### PR TITLE
Implement a force_update option for sync command

### PR DESCRIPTION
**Pull request by jeanpommier**
Sometimes, it seems CKAN misses some information it should patch, particularly the image possibly attached to an organization. You might then need, in such cases, to force an update on every entries.

### CODE REVIEW

**Comment by fvanderbiest** [comment]
Thanks Jean.
@RemiDesgrange will have a look but it looks good to me.

**Comment by fvanderbiest** [comment]
Remi being unavailable for some time, I had a look and it looks good.
Wondering though if we should not be consistent and adopt the same strategy for updating Organizations and Users (comparing fields). Moreover if what CKAN provides is more or less broken...

**Comment by jeanpommier** [comment]
To be discussed...

**Comment by fvanderbiest** [comment]
Ok, thanks for merging. Let's see how it goes

**Pull request merged**
